### ISSUE TITLE
Update to Cloudstack 4.13 LTS

### ISSUE THREAD

**Issue by rvalle** [ansible/cloudstack-test-container#11]
So that we can test hew features being implemented 

For details:

https://github.com/ngine-io/ansible-collection-cloudstack/issues/32

**Comment by rvalle** [comment]
@resmo I wonder if it is better to try to upgrade to ubuntu 18.04 python/3 or just workaround the problem.

I did a quick test and the image fails earlier than with the current image.

I run everything for ACS 4.14 on Ubuntu18/Python 3, but I am not sure if 4.13 or the emulator work the same.

**Comment by resmo** [comment]
ACS 4.14 would be fine if the effort is not worth it to make 4.13 work.

**Comment by rvalle** [comment]
I will check that strategy too.
